### ISSUE TITLE
if possible make a recipe to make one tool of choice

### ISSUE THREAD

**Issue by Blokkiesam** [Dimmerworld/MoObsidian#4]
title ^ if not possible no worries

**Comment by Dimmerworld** [comment]
What do you mean? add a recipe for the obsidian pickaxe?

**Comment by Dimmerworld** [comment]
Made Obsidian pickaxe recipe 
![capture](https://cloud.githubusercontent.com/assets/4002351/24447973/708c84fe-14be-11e7-9b0f-9377f23c716d.PNG)
